### ISSUE TITLE
Minimize number of props and states

### ISSUE THREAD

**Issue by syaau** [sharingapples/react-native-calendar#3]
1. Month component has two props `start` and `month`. I guess, month should have been enough here.
2. `date` and `months`, seem like storing the same state values.
3. `multipleSelect` seems redundant. Looks like the selection hasn't been implemented the way we discussed it.

**Comment by karkipy** [comment]
@syaau I guess is addressing https://github.com/sharingapples/react-native-calendar/issues/6 will resolve the issue for multipleSelect,

**Comment by karkipy** [comment]
date & month are different where month is an array of how many months to show in a screen

**Comment by syaau** [comment]
Well how I see it in the code is they are both storing the same value and the usage of `date` can easily be replaced with the month value.

**Comment by karkipy** [comment]
@syaau dai, month is storing the current date and the next month's date as well

**Comment by karkipy** [comment]
marking this as done
