### ISSUE TITLE
Use @sharingapples/theme package to define theme.

### ISSUE THREAD

**Issue by syaau** [sharingapples/react-native-calendar#4]

**Comment by karkipy** [comment]
@syaau  dai isn't the implementation on app level , we only need to add  theme package in peer dependencies ?

**Comment by syaau** [comment]
Yes, that's true, but you need to use that package in the widget.

**Comment by karkipy** [comment]
@syaau , i forgot to update the latest version with theme, i got it

**Comment by karkipy** [comment]
marking this as done
